### ISSUE TITLE
Correct Oric image conversion.

### ISSUE THREAD

**Issue by haroldo-ok** [haroldo-ok/8bit-Unity#1]
As recommended by @8bit-Dude: For Oric, the algorithm should ideally resize PNG to 234x200, then add 6 columns of black pixels on the left-side (which is used for setting color attributes) to make the final 240x200 image.

**Comment by 8bit-Dude** [comment]
Thanks in advance buddy!

**Comment by 8bit-Dude** [comment]
I just remembered one thing: Does the script recognize cases where the image is already in correct format (i.e: correct resolution and palette with correct number of colors), in which case it skips the file?

**Comment by haroldo-ok** [comment]
No, currently, it always overwrites the output files.

**Comment by haroldo-ok** [comment]
Corrected by https://github.com/haroldo-ok/8bit-Unity/commit/1dfeca23075abde99fe29781fabc1add962fc7a3
